use std::fs;
use std::path::Path;

#[test]
fn runtime_owns_no_interface_source_or_emitter() {
    let root = Path::new(env!("CARGO_MANIFEST_DIR"));
    assert!(!root.join("build.rs").exists());
    assert!(!root.join("schema").exists());
    assert!(!root.join("src/schema").exists());

    let manifest = fs::read_to_string(root.join("Cargo.toml")).expect("read Cargo.toml");
    assert!(!manifest.contains("[build-dependencies]"));
    assert!(!manifest.contains("schema-rust"));
    assert!(!manifest.contains("schema.git"));

    let library = fs::read_to_string(root.join("src/lib.rs")).expect("read src/lib.rs");
    assert!(!library.contains("pub use signal_router"));
    assert!(!library.contains("pub use meta_signal_router"));

    let forbidden = [
        "@generated by schema-rust",
        "GenerationDriver",
        "GenerationPlan",
        "ModuleEmission",
        "ContractCrateBuild",
        "DependencySchema",
        "CargoSchemaMetadata",
    ];
    let mut pending = vec![root.join("src")];
    while let Some(path) = pending.pop() {
        for entry in fs::read_dir(path).expect("read source directory") {
            let path = entry.expect("read source entry").path();
            if path.is_dir() {
                pending.push(path);
            } else if path.extension().is_some_and(|extension| extension == "rs") {
                let source = fs::read_to_string(&path).expect("read Rust source");
                for name in forbidden {
                    assert!(
                        !source.contains(name),
                        "{} retains deleted emitter ownership marker {name}",
                        path.display()
                    );
                }
            }
        }
    }
}
