// @generated by schema-rust-next

#[rustfmt::skip]
pub type String = std::string::String;
#[rustfmt::skip]
pub type Integer = u64;
#[rustfmt::skip]
pub type Boolean = bool;
#[rustfmt::skip]
pub type Path = std::string::String;

#[rustfmt::skip]
pub use crate::schema::signal::Input as SignalInput;
#[rustfmt::skip]
pub use crate::schema::signal::Output as SignalOutput;
#[rustfmt::skip]
pub use crate::schema::signal::MessageIngress as MessageIngress;
#[rustfmt::skip]
pub use crate::schema::signal::MessageAcceptance as MessageAcceptance;
#[rustfmt::skip]
pub use crate::schema::signal::AdjudicationQueued as AdjudicationQueued;
#[rustfmt::skip]
pub use crate::schema::signal::ErrorReport as ErrorReport;
#[rustfmt::skip]
pub use crate::schema::sema::WriteInput as SemaWriteInput;
#[rustfmt::skip]
pub use crate::schema::sema::ReadInput as SemaReadInput;
#[rustfmt::skip]
pub use crate::schema::sema::WriteOutput as SemaWriteOutput;
#[rustfmt::skip]
pub use crate::schema::sema::ReadOutput as SemaReadOutput;

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
pub use nota_next::{NotaDecode, NotaDecodeError, NotaEncode, NotaSource};

#[rustfmt::skip]
pub type SignalArrived = SignalInput;

#[rustfmt::skip]
pub type SemaWriteCompleted = SemaWriteOutput;

#[rustfmt::skip]
pub type SemaReadCompleted = SemaReadOutput;

#[rustfmt::skip]
pub type EffectCompleted = NexusEffectResult;

#[rustfmt::skip]
pub type ReplyToSignal = SignalOutput;

#[rustfmt::skip]
pub type CommandSemaWrite = SemaWriteInput;

#[rustfmt::skip]
pub type CommandSemaRead = SemaReadInput;

#[rustfmt::skip]
pub type CommandEffect = NexusEffectCommand;

#[rustfmt::skip]
pub type Continue = NexusWork;

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum NexusWork {
    SignalArrived(SignalArrived),
    SemaWriteCompleted(SemaWriteCompleted),
    SemaReadCompleted(SemaReadCompleted),
    EffectCompleted(EffectCompleted),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum NexusAction {
    ReplyToSignal(ReplyToSignal),
    CommandSemaWrite(CommandSemaWrite),
    CommandSemaRead(CommandSemaRead),
    CommandEffect(CommandEffect),
    Continue(Continue),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum DeliveryCommand {
    AttemptDelivery(AttemptDelivery),
    RequestAdjudication(RequestAdjudication),
}

#[rustfmt::skip]
pub type AttemptDelivery = MessageIngress;

#[rustfmt::skip]
pub type RequestAdjudication = MessageIngress;

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum NexusEffectCommand {
    DeliverToHarness(DeliverToHarness),
    AskMindForChannel(AskMindForChannel),
}

#[rustfmt::skip]
pub type DeliverToHarness = DeliveryCommand;

#[rustfmt::skip]
pub type AskMindForChannel = MessageIngress;

#[rustfmt::skip]
pub type DeliverySucceeded = MessageAcceptance;

#[rustfmt::skip]
pub type DeliveryParked = AdjudicationQueued;

#[rustfmt::skip]
pub type DeliveryFailed = ErrorReport;

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum NexusEffectResult {
    DeliverySucceeded(DeliverySucceeded),
    DeliveryParked(DeliveryParked),
    DeliveryFailed(DeliveryFailed),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    SignalArrived(SignalArrived),
    SemaWriteCompleted(SemaWriteCompleted),
    SemaReadCompleted(SemaReadCompleted),
    EffectCompleted(EffectCompleted),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    ReplyToSignal(ReplyToSignal),
    CommandSemaWrite(CommandSemaWrite),
    CommandSemaRead(CommandSemaRead),
    CommandEffect(CommandEffect),
    Continue(Continue),
}

#[rustfmt::skip]
impl NexusWork {
    pub fn signal_arrived(payload: SignalArrived) -> Self {
        Self::SignalArrived(payload)
    }
    pub fn sema_write_completed(payload: SemaWriteCompleted) -> Self {
        Self::SemaWriteCompleted(payload)
    }
    pub fn sema_read_completed(payload: SemaReadCompleted) -> Self {
        Self::SemaReadCompleted(payload)
    }
    pub fn effect_completed(payload: EffectCompleted) -> Self {
        Self::EffectCompleted(payload)
    }
}

#[rustfmt::skip]
impl NexusAction {
    pub fn reply_to_signal(payload: ReplyToSignal) -> Self {
        Self::ReplyToSignal(payload)
    }
    pub fn command_sema_write(payload: CommandSemaWrite) -> Self {
        Self::CommandSemaWrite(payload)
    }
    pub fn command_sema_read(payload: CommandSemaRead) -> Self {
        Self::CommandSemaRead(payload)
    }
    pub fn command_effect(payload: CommandEffect) -> Self {
        Self::CommandEffect(payload)
    }
    pub fn r#continue(payload: Continue) -> Self {
        Self::Continue(payload)
    }
}

#[rustfmt::skip]
impl DeliveryCommand {
    pub fn attempt_delivery(payload: AttemptDelivery) -> Self {
        Self::AttemptDelivery(payload)
    }
    pub fn request_adjudication(payload: RequestAdjudication) -> Self {
        Self::RequestAdjudication(payload)
    }
}

#[rustfmt::skip]
impl NexusEffectCommand {
    pub fn deliver_to_harness(payload: DeliverToHarness) -> Self {
        Self::DeliverToHarness(payload)
    }
    pub fn ask_mind_for_channel(payload: AskMindForChannel) -> Self {
        Self::AskMindForChannel(payload)
    }
}

#[rustfmt::skip]
impl NexusEffectResult {
    pub fn delivery_succeeded(payload: DeliverySucceeded) -> Self {
        Self::DeliverySucceeded(payload)
    }
    pub fn delivery_parked(payload: DeliveryParked) -> Self {
        Self::DeliveryParked(payload)
    }
    pub fn delivery_failed(payload: DeliveryFailed) -> Self {
        Self::DeliveryFailed(payload)
    }
}

#[rustfmt::skip]
impl Input {
    pub fn signal_arrived(payload: SignalArrived) -> Self {
        Self::SignalArrived(payload)
    }
    pub fn sema_write_completed(payload: SemaWriteCompleted) -> Self {
        Self::SemaWriteCompleted(payload)
    }
    pub fn sema_read_completed(payload: SemaReadCompleted) -> Self {
        Self::SemaReadCompleted(payload)
    }
    pub fn effect_completed(payload: EffectCompleted) -> Self {
        Self::EffectCompleted(payload)
    }
}

#[rustfmt::skip]
impl Output {
    pub fn reply_to_signal(payload: ReplyToSignal) -> Self {
        Self::ReplyToSignal(payload)
    }
    pub fn command_sema_write(payload: CommandSemaWrite) -> Self {
        Self::CommandSemaWrite(payload)
    }
    pub fn command_sema_read(payload: CommandSemaRead) -> Self {
        Self::CommandSemaRead(payload)
    }
    pub fn command_effect(payload: CommandEffect) -> Self {
        Self::CommandEffect(payload)
    }
    pub fn r#continue(payload: Continue) -> Self {
        Self::Continue(payload)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl NexusWork {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl NexusAction {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl DeliveryCommand {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl NexusEffectCommand {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl NexusEffectResult {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Input {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Input {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Output {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Output {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum NexusWorkRoute {
    SignalArrived,
    SemaWriteCompleted,
    SemaReadCompleted,
    EffectCompleted,
}

#[rustfmt::skip]
impl NexusWork {
    pub fn route(&self) -> NexusWorkRoute {
        match self {
            Self::SignalArrived(_) => NexusWorkRoute::SignalArrived,
            Self::SemaWriteCompleted(_) => NexusWorkRoute::SemaWriteCompleted,
            Self::SemaReadCompleted(_) => NexusWorkRoute::SemaReadCompleted,
            Self::EffectCompleted(_) => NexusWorkRoute::EffectCompleted,
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum NexusActionRoute {
    ReplyToSignal,
    CommandSemaWrite,
    CommandSemaRead,
    CommandEffect,
    Continue,
}

#[rustfmt::skip]
impl NexusAction {
    pub fn route(&self) -> NexusActionRoute {
        match self {
            Self::ReplyToSignal(_) => NexusActionRoute::ReplyToSignal,
            Self::CommandSemaWrite(_) => NexusActionRoute::CommandSemaWrite,
            Self::CommandSemaRead(_) => NexusActionRoute::CommandSemaRead,
            Self::CommandEffect(_) => NexusActionRoute::CommandEffect,
            Self::Continue(_) => NexusActionRoute::Continue,
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum NexusObjectName {
    Work(NexusWorkRoute),
    Action(NexusActionRoute),
    Started,
    Stopped,
    Entered,
    Decided,
}
#[rustfmt::skip]
impl NexusObjectName {
    pub fn name(self) -> &'static str {
        match self {
            Self::Work(route) => {
                match route {
                    NexusWorkRoute::SignalArrived => "NexusWorkSignalArrived",
                    NexusWorkRoute::SemaWriteCompleted => "NexusWorkSemaWriteCompleted",
                    NexusWorkRoute::SemaReadCompleted => "NexusWorkSemaReadCompleted",
                    NexusWorkRoute::EffectCompleted => "NexusWorkEffectCompleted",
                }
            }
            Self::Action(route) => {
                match route {
                    NexusActionRoute::ReplyToSignal => "NexusActionReplyToSignal",
                    NexusActionRoute::CommandSemaWrite => "NexusActionCommandSemaWrite",
                    NexusActionRoute::CommandSemaRead => "NexusActionCommandSemaRead",
                    NexusActionRoute::CommandEffect => "NexusActionCommandEffect",
                    NexusActionRoute::Continue => "NexusActionContinue",
                }
            }
            Self::Started => "NexusStarted",
            Self::Stopped => "NexusStopped",
            Self::Entered => "NexusEntered",
            Self::Decided => "NexusDecided",
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ObjectName {
    Nexus(NexusObjectName),
}
#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub struct TraceEvent(pub ObjectName);
#[rustfmt::skip]
impl ObjectName {
    pub fn name(self) -> &'static str {
        match self {
            Self::Nexus(object_name) => object_name.name(),
        }
    }
}
#[rustfmt::skip]
impl TraceEvent {
    pub fn new(object_name: ObjectName) -> Self {
        Self(object_name)
    }
    pub fn object_name(&self) -> ObjectName {
        self.0
    }
    pub fn name(&self) -> &'static str {
        self.0.name()
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub struct OriginRoute(pub Integer);
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl OriginRoute {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(self) -> String {
        <Self as NotaEncode>::to_nota(&self)
    }
}

#[rustfmt::skip]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Nexus<Root> {
    pub origin_route: OriginRoute,
    pub root: Root,
}
#[rustfmt::skip]
impl<Root> Nexus<Root> {
    pub fn new(origin_route: OriginRoute, root: Root) -> Self {
        Self { origin_route, root }
    }
    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }
    pub fn root(&self) -> &Root {
        &self.root
    }
    pub fn into_root(self) -> Root {
        self.root
    }
    pub fn map_root<NextRoot>(
        self,
        map: impl FnOnce(Root) -> NextRoot,
    ) -> Nexus<NextRoot> {
        Nexus::new(self.origin_route, map(self.root))
    }
}

#[rustfmt::skip]
#[allow(clippy::module_inception)]
pub mod nexus {
    pub type Work = super::NexusWork;
    pub type Action = super::NexusAction;
    pub type Nexus<Root> = super::Nexus<Root>;
}

#[rustfmt::skip]
impl NexusWork {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> nexus::Nexus<Self> {
        nexus::Nexus::new(origin_route, self)
    }
}

#[rustfmt::skip]
impl NexusAction {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> nexus::Nexus<Self> {
        nexus::Nexus::new(origin_route, self)
    }
}

#[rustfmt::skip]
impl triad_runtime::NexusWork for NexusWork {}

#[rustfmt::skip]
impl triad_runtime::NexusEffectCommand for CommandEffect {}

#[rustfmt::skip]
impl triad_runtime::NexusEffectResult for EffectCompleted {}

#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum EngineStartFailure {
    ResourceBusy(String),
    ConfigurationInvalid(String),
}
#[rustfmt::skip]
impl std::fmt::Display for EngineStartFailure {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ResourceBusy(message) => {
                write!(formatter, "engine resource busy: {message}")
            }
            Self::ConfigurationInvalid(message) => {
                write!(formatter, "engine configuration invalid: {message}")
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for EngineStartFailure {}
#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum EngineStopFailure {
    ResourceLocked(String),
    ChildStillRunning(String),
}
#[rustfmt::skip]
impl std::fmt::Display for EngineStopFailure {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ResourceLocked(message) => {
                write!(formatter, "engine resource locked: {message}")
            }
            Self::ChildStillRunning(message) => {
                write!(formatter, "engine child still running: {message}")
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for EngineStopFailure {}

#[rustfmt::skip]
pub type NexusRunnerNextStep = triad_runtime::NextStep<
    ReplyToSignal,
    CommandSemaWrite,
    CommandSemaRead,
    CommandEffect,
    NexusWork,
>;
#[rustfmt::skip]
impl triad_runtime::NexusAction for NexusAction {
    type Reply = ReplyToSignal;
    type SemaWrite = CommandSemaWrite;
    type SemaRead = CommandSemaRead;
    type Effect = CommandEffect;
    type Work = NexusWork;
    fn into_next_step(self) -> NexusRunnerNextStep {
        match self {
            Self::CommandSemaWrite(input) => triad_runtime::NextStep::SemaWrite(input),
            Self::CommandSemaRead(input) => triad_runtime::NextStep::SemaRead(input),
            Self::ReplyToSignal(output) => triad_runtime::NextStep::Reply(output),
            Self::CommandEffect(effect) => triad_runtime::NextStep::RunEffect(effect),
            Self::Continue(work) => triad_runtime::NextStep::Continue(work),
        }
    }
}

#[rustfmt::skip]
pub trait NexusEngine: Send {
    fn on_start(&mut self) -> Result<(), EngineStartFailure> {
        Ok(())
    }
    fn on_stop(&mut self) -> Result<(), EngineStopFailure> {
        Ok(())
    }
    fn trace_nexus_activation(&self, _object_name: NexusObjectName) {}
    fn trace_nexus_entered(&self) {
        self.trace_nexus_activation(NexusObjectName::Entered);
    }
    fn trace_nexus_decided(&self) {
        self.trace_nexus_activation(NexusObjectName::Decided);
    }
    fn continuation_limit(&self) -> triad_runtime::ContinuationLimit {
        triad_runtime::ContinuationLimit::default()
    }
    fn apply_sema_write(
        &mut self,
        origin_route: OriginRoute,
        input: CommandSemaWrite,
    ) -> impl std::future::Future<Output = SemaWriteCompleted> + Send + '_;
    fn observe_sema_read(
        &mut self,
        origin_route: OriginRoute,
        input: CommandSemaRead,
    ) -> impl std::future::Future<Output = SemaReadCompleted> + Send + '_;
    fn run_effect(
        &mut self,
        input: CommandEffect,
    ) -> impl std::future::Future<Output = EffectCompleted> + Send + '_;
    fn budget_exhausted_reply(
        &self,
        exhausted: triad_runtime::ContinuationExhausted,
    ) -> ReplyToSignal;
    fn decide(
        &mut self,
        input: nexus::Nexus<nexus::Work>,
    ) -> nexus::Nexus<nexus::Action>;
    fn execute(
        &mut self,
        input: nexus::Nexus<nexus::Work>,
    ) -> impl std::future::Future<Output = nexus::Nexus<nexus::Action>> + Send + '_
    where
        Self: Sized,
    {
        async move {
            self.trace_nexus_entered();
            let origin_route = input.origin_route();
            let first_work = input.into_root();
            let runner = triad_runtime::Runner::new(self.continuation_limit());
            let mut runner_adapter = NexusRunnerAdapter::new(self, origin_route);
            let reply = runner.drive(&mut runner_adapter, first_work).await;
            let output = NexusAction::reply_to_signal(reply)
                .with_origin_route(origin_route);
            self.trace_nexus_decided();
            output
        }
    }
}

#[rustfmt::skip]
struct NexusRunnerAdapter<'engine, Engine> {
    engine: &'engine mut Engine,
    origin_route: OriginRoute,
}
#[rustfmt::skip]
impl<'engine, Engine> NexusRunnerAdapter<'engine, Engine> {
    fn new(engine: &'engine mut Engine, origin_route: OriginRoute) -> Self {
        Self { engine, origin_route }
    }
}
#[rustfmt::skip]
impl<'engine, Engine> triad_runtime::RunnerEngines
for NexusRunnerAdapter<'engine, Engine>
where
    Engine: NexusEngine,
{
    type Reply = ReplyToSignal;
    type SemaWrite = CommandSemaWrite;
    type SemaRead = CommandSemaRead;
    type Effect = CommandEffect;
    type Work = NexusWork;
    fn decide_next_step(
        &mut self,
        work: Self::Work,
    ) -> triad_runtime::runner::RunnerNextStep<Self> {
        let action = NexusEngine::decide(
                self.engine,
                work.with_origin_route(self.origin_route),
            )
            .into_root();
        triad_runtime::NexusAction::into_next_step(action)
    }
    async fn apply_sema_write(&mut self, write: Self::SemaWrite) -> Self::Work {
        let output: SemaWriteCompleted = NexusEngine::apply_sema_write(
                self.engine,
                self.origin_route,
                write,
            )
            .await;
        NexusWork::sema_write_completed(output)
    }
    async fn observe_sema_read(&mut self, read: Self::SemaRead) -> Self::Work {
        let output: SemaReadCompleted = NexusEngine::observe_sema_read(
                self.engine,
                self.origin_route,
                read,
            )
            .await;
        NexusWork::sema_read_completed(output)
    }
    async fn run_effect(&mut self, effect: Self::Effect) -> Self::Work {
        let output: EffectCompleted = NexusEngine::run_effect(self.engine, effect).await;
        NexusWork::effect_completed(output)
    }
    fn budget_exhausted_reply(
        &self,
        exhausted: triad_runtime::ContinuationExhausted,
    ) -> Self::Reply {
        NexusEngine::budget_exhausted_reply(self.engine, exhausted)
    }
}

#[rustfmt::skip]
pub trait UpgradeFrom<Previous>: Sized {
    type Error;
    fn upgrade_from(previous: Previous) -> Result<Self, Self::Error>;
}
#[rustfmt::skip]
pub trait AcceptPrevious<Previous>: UpgradeFrom<Previous> {
    fn accept_previous(previous: Previous) -> Result<Self, Self::Error> {
        Self::upgrade_from(previous)
    }
}
#[rustfmt::skip]
impl<Current, Previous> AcceptPrevious<Previous> for Current
where
    Current: UpgradeFrom<Previous>,
{}
