// @generated by schema-rust

#[rustfmt::skip]
pub type String = std::string::String;
#[rustfmt::skip]
pub type Integer = u64;
#[rustfmt::skip]
pub type Boolean = bool;
#[rustfmt::skip]
pub type Path = std::string::String;

#[rustfmt::skip]
pub use crate::schema::signal::Input as SignalInput;
#[rustfmt::skip]
pub use crate::schema::signal::Output as SignalOutput;
#[rustfmt::skip]
pub use crate::schema::signal::MessageIngress as MessageIngress;
#[rustfmt::skip]
pub use crate::schema::signal::MessageAcceptance as MessageAcceptance;
#[rustfmt::skip]
pub use crate::schema::signal::AdjudicationQueued as AdjudicationQueued;
#[rustfmt::skip]
pub use crate::schema::signal::ErrorReport as ErrorReport;
#[rustfmt::skip]
pub use crate::schema::sema::WriteInput as SemaWriteInput;
#[rustfmt::skip]
pub use crate::schema::sema::ReadInput as SemaReadInput;
#[rustfmt::skip]
pub use crate::schema::sema::WriteOutput as SemaWriteOutput;
#[rustfmt::skip]
pub use crate::schema::sema::ReadOutput as SemaReadOutput;

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
pub use nota::{NotaDecodeError, NotaEncode, NotaSource};

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Work<Event, WriteDone, ReadDone, EffectDone> {
    SignalArrived(Event),
    SemaWriteCompleted(WriteDone),
    SemaReadCompleted(ReadDone),
    EffectCompleted(EffectDone),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Action<Reply, Write, Read, Effect, Continuation> {
    ReplyToSignal(Reply),
    CommandSemaWrite(Write),
    CommandSemaRead(Read),
    CommandEffect(Effect),
    Continue(Continuation),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum NexusWork {
    SignalArrived(SignalInput),
    SemaWriteCompleted(SemaWriteOutput),
    SemaReadCompleted(SemaReadOutput),
    EffectCompleted(NexusEffectResult),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum NexusAction {
    ReplyToSignal(SignalOutput),
    CommandSemaWrite(SemaWriteInput),
    CommandSemaRead(SemaReadInput),
    CommandEffect(NexusEffectCommand),
    Continue(NexusWork),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum DeliveryCommand {
    AttemptDelivery(AttemptDelivery),
    RequestAdjudication(RequestAdjudication),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AttemptDelivery(MessageIngress);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RequestAdjudication(MessageIngress);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum NexusEffectCommand {
    DeliverToHarness(DeliverToHarness),
    AskMindForChannel(AskMindForChannel),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DeliverToHarness(DeliveryCommand);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AskMindForChannel(MessageIngress);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DeliverySucceeded(MessageAcceptance);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DeliveryParked(AdjudicationQueued);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DeliveryFailed(ErrorReport);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum NexusEffectResult {
    DeliverySucceeded(DeliverySucceeded),
    DeliveryParked(DeliveryParked),
    DeliveryFailed(DeliveryFailed),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    SignalArrived(SignalInput),
    SemaWriteCompleted(SemaWriteOutput),
    SemaReadCompleted(SemaReadOutput),
    EffectCompleted(NexusEffectResult),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    ReplyToSignal(SignalOutput),
    CommandSemaWrite(SemaWriteInput),
    CommandSemaRead(SemaReadInput),
    CommandEffect(NexusEffectCommand),
    Continue(Input),
}

#[rustfmt::skip]
impl AttemptDelivery {
    pub fn new(payload: MessageIngress) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &MessageIngress {
        &self.0
    }
    pub fn into_payload(self) -> MessageIngress {
        self.0
    }
}
#[rustfmt::skip]
impl From<MessageIngress> for AttemptDelivery {
    fn from(payload: MessageIngress) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RequestAdjudication {
    pub fn new(payload: MessageIngress) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &MessageIngress {
        &self.0
    }
    pub fn into_payload(self) -> MessageIngress {
        self.0
    }
}
#[rustfmt::skip]
impl From<MessageIngress> for RequestAdjudication {
    fn from(payload: MessageIngress) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl DeliverToHarness {
    pub fn new(payload: DeliveryCommand) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &DeliveryCommand {
        &self.0
    }
    pub fn into_payload(self) -> DeliveryCommand {
        self.0
    }
}
#[rustfmt::skip]
impl From<DeliveryCommand> for DeliverToHarness {
    fn from(payload: DeliveryCommand) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl AskMindForChannel {
    pub fn new(payload: MessageIngress) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &MessageIngress {
        &self.0
    }
    pub fn into_payload(self) -> MessageIngress {
        self.0
    }
}
#[rustfmt::skip]
impl From<MessageIngress> for AskMindForChannel {
    fn from(payload: MessageIngress) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl DeliverySucceeded {
    pub fn new(payload: MessageAcceptance) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &MessageAcceptance {
        &self.0
    }
    pub fn into_payload(self) -> MessageAcceptance {
        self.0
    }
}
#[rustfmt::skip]
impl From<MessageAcceptance> for DeliverySucceeded {
    fn from(payload: MessageAcceptance) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl DeliveryParked {
    pub fn new(payload: AdjudicationQueued) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &AdjudicationQueued {
        &self.0
    }
    pub fn into_payload(self) -> AdjudicationQueued {
        self.0
    }
}
#[rustfmt::skip]
impl From<AdjudicationQueued> for DeliveryParked {
    fn from(payload: AdjudicationQueued) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl DeliveryFailed {
    pub fn new(payload: ErrorReport) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ErrorReport {
        &self.0
    }
    pub fn into_payload(self) -> ErrorReport {
        self.0
    }
}
#[rustfmt::skip]
impl From<ErrorReport> for DeliveryFailed {
    fn from(payload: ErrorReport) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl NexusWork {
    pub fn signal_arrived(payload: SignalInput) -> Self {
        Self::SignalArrived(payload)
    }
    pub fn sema_write_completed(payload: SemaWriteOutput) -> Self {
        Self::SemaWriteCompleted(payload)
    }
    pub fn sema_read_completed(payload: SemaReadOutput) -> Self {
        Self::SemaReadCompleted(payload)
    }
    pub fn effect_completed(payload: NexusEffectResult) -> Self {
        Self::EffectCompleted(payload)
    }
}

#[rustfmt::skip]
impl NexusAction {
    pub fn reply_to_signal(payload: SignalOutput) -> Self {
        Self::ReplyToSignal(payload)
    }
    pub fn command_sema_write(payload: SemaWriteInput) -> Self {
        Self::CommandSemaWrite(payload)
    }
    pub fn command_sema_read(payload: SemaReadInput) -> Self {
        Self::CommandSemaRead(payload)
    }
    pub fn command_effect(payload: NexusEffectCommand) -> Self {
        Self::CommandEffect(payload)
    }
    pub fn r#continue(payload: NexusWork) -> Self {
        Self::Continue(payload)
    }
}

#[rustfmt::skip]
impl DeliveryCommand {
    pub fn attempt_delivery(payload: MessageIngress) -> Self {
        Self::AttemptDelivery(AttemptDelivery::new(payload))
    }
    pub fn request_adjudication(payload: MessageIngress) -> Self {
        Self::RequestAdjudication(RequestAdjudication::new(payload))
    }
}

#[rustfmt::skip]
impl NexusEffectCommand {
    pub fn deliver_to_harness(payload: DeliveryCommand) -> Self {
        Self::DeliverToHarness(DeliverToHarness::new(payload))
    }
    pub fn ask_mind_for_channel(payload: MessageIngress) -> Self {
        Self::AskMindForChannel(AskMindForChannel::new(payload))
    }
}

#[rustfmt::skip]
impl NexusEffectResult {
    pub fn delivery_succeeded(payload: MessageAcceptance) -> Self {
        Self::DeliverySucceeded(DeliverySucceeded::new(payload))
    }
    pub fn delivery_parked(payload: AdjudicationQueued) -> Self {
        Self::DeliveryParked(DeliveryParked::new(payload))
    }
    pub fn delivery_failed(payload: ErrorReport) -> Self {
        Self::DeliveryFailed(DeliveryFailed::new(payload))
    }
}

#[rustfmt::skip]
impl Input {
    pub fn signal_arrived(payload: SignalInput) -> Self {
        Self::SignalArrived(payload)
    }
    pub fn sema_write_completed(payload: SemaWriteOutput) -> Self {
        Self::SemaWriteCompleted(payload)
    }
    pub fn sema_read_completed(payload: SemaReadOutput) -> Self {
        Self::SemaReadCompleted(payload)
    }
    pub fn effect_completed(payload: NexusEffectResult) -> Self {
        Self::EffectCompleted(payload)
    }
}

#[rustfmt::skip]
impl Output {
    pub fn reply_to_signal(payload: SignalOutput) -> Self {
        Self::ReplyToSignal(payload)
    }
    pub fn command_sema_write(payload: SemaWriteInput) -> Self {
        Self::CommandSemaWrite(payload)
    }
    pub fn command_sema_read(payload: SemaReadInput) -> Self {
        Self::CommandSemaRead(payload)
    }
    pub fn command_effect(payload: NexusEffectCommand) -> Self {
        Self::CommandEffect(payload)
    }
    pub fn r#continue(payload: Input) -> Self {
        Self::Continue(payload)
    }
}

#[rustfmt::skip]
impl From<SignalInput> for NexusWork {
    fn from(payload: SignalInput) -> Self {
        Self::SignalArrived(payload)
    }
}

#[rustfmt::skip]
impl From<SemaWriteOutput> for NexusWork {
    fn from(payload: SemaWriteOutput) -> Self {
        Self::SemaWriteCompleted(payload)
    }
}

#[rustfmt::skip]
impl From<SemaReadOutput> for NexusWork {
    fn from(payload: SemaReadOutput) -> Self {
        Self::SemaReadCompleted(payload)
    }
}

#[rustfmt::skip]
impl From<NexusEffectResult> for NexusWork {
    fn from(payload: NexusEffectResult) -> Self {
        Self::EffectCompleted(payload)
    }
}

#[rustfmt::skip]
impl From<SignalOutput> for NexusAction {
    fn from(payload: SignalOutput) -> Self {
        Self::ReplyToSignal(payload)
    }
}

#[rustfmt::skip]
impl From<SemaWriteInput> for NexusAction {
    fn from(payload: SemaWriteInput) -> Self {
        Self::CommandSemaWrite(payload)
    }
}

#[rustfmt::skip]
impl From<SemaReadInput> for NexusAction {
    fn from(payload: SemaReadInput) -> Self {
        Self::CommandSemaRead(payload)
    }
}

#[rustfmt::skip]
impl From<NexusEffectCommand> for NexusAction {
    fn from(payload: NexusEffectCommand) -> Self {
        Self::CommandEffect(payload)
    }
}

#[rustfmt::skip]
impl From<NexusWork> for NexusAction {
    fn from(payload: NexusWork) -> Self {
        Self::Continue(payload)
    }
}

#[rustfmt::skip]
impl From<AttemptDelivery> for DeliveryCommand {
    fn from(payload: AttemptDelivery) -> Self {
        Self::AttemptDelivery(payload)
    }
}

#[rustfmt::skip]
impl From<RequestAdjudication> for DeliveryCommand {
    fn from(payload: RequestAdjudication) -> Self {
        Self::RequestAdjudication(payload)
    }
}

#[rustfmt::skip]
impl From<DeliverToHarness> for NexusEffectCommand {
    fn from(payload: DeliverToHarness) -> Self {
        Self::DeliverToHarness(payload)
    }
}

#[rustfmt::skip]
impl From<AskMindForChannel> for NexusEffectCommand {
    fn from(payload: AskMindForChannel) -> Self {
        Self::AskMindForChannel(payload)
    }
}

#[rustfmt::skip]
impl From<DeliverySucceeded> for NexusEffectResult {
    fn from(payload: DeliverySucceeded) -> Self {
        Self::DeliverySucceeded(payload)
    }
}

#[rustfmt::skip]
impl From<DeliveryParked> for NexusEffectResult {
    fn from(payload: DeliveryParked) -> Self {
        Self::DeliveryParked(payload)
    }
}

#[rustfmt::skip]
impl From<DeliveryFailed> for NexusEffectResult {
    fn from(payload: DeliveryFailed) -> Self {
        Self::DeliveryFailed(payload)
    }
}

#[rustfmt::skip]
impl From<SignalInput> for Input {
    fn from(payload: SignalInput) -> Self {
        Self::SignalArrived(payload)
    }
}

#[rustfmt::skip]
impl From<SemaWriteOutput> for Input {
    fn from(payload: SemaWriteOutput) -> Self {
        Self::SemaWriteCompleted(payload)
    }
}

#[rustfmt::skip]
impl From<SemaReadOutput> for Input {
    fn from(payload: SemaReadOutput) -> Self {
        Self::SemaReadCompleted(payload)
    }
}

#[rustfmt::skip]
impl From<NexusEffectResult> for Input {
    fn from(payload: NexusEffectResult) -> Self {
        Self::EffectCompleted(payload)
    }
}

#[rustfmt::skip]
impl From<SignalOutput> for Output {
    fn from(payload: SignalOutput) -> Self {
        Self::ReplyToSignal(payload)
    }
}

#[rustfmt::skip]
impl From<SemaWriteInput> for Output {
    fn from(payload: SemaWriteInput) -> Self {
        Self::CommandSemaWrite(payload)
    }
}

#[rustfmt::skip]
impl From<SemaReadInput> for Output {
    fn from(payload: SemaReadInput) -> Self {
        Self::CommandSemaRead(payload)
    }
}

#[rustfmt::skip]
impl From<NexusEffectCommand> for Output {
    fn from(payload: NexusEffectCommand) -> Self {
        Self::CommandEffect(payload)
    }
}

#[rustfmt::skip]
impl From<Input> for Output {
    fn from(payload: Input) -> Self {
        Self::Continue(payload)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Input {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Output {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum NexusWorkRoute {
    SignalArrived,
    SemaWriteCompleted,
    SemaReadCompleted,
    EffectCompleted,
}

#[rustfmt::skip]
impl NexusWork {
    pub fn route(&self) -> NexusWorkRoute {
        match self {
            Self::SignalArrived(_) => NexusWorkRoute::SignalArrived,
            Self::SemaWriteCompleted(_) => NexusWorkRoute::SemaWriteCompleted,
            Self::SemaReadCompleted(_) => NexusWorkRoute::SemaReadCompleted,
            Self::EffectCompleted(_) => NexusWorkRoute::EffectCompleted,
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum NexusActionRoute {
    ReplyToSignal,
    CommandSemaWrite,
    CommandSemaRead,
    CommandEffect,
    Continue,
}

#[rustfmt::skip]
impl NexusAction {
    pub fn route(&self) -> NexusActionRoute {
        match self {
            Self::ReplyToSignal(_) => NexusActionRoute::ReplyToSignal,
            Self::CommandSemaWrite(_) => NexusActionRoute::CommandSemaWrite,
            Self::CommandSemaRead(_) => NexusActionRoute::CommandSemaRead,
            Self::CommandEffect(_) => NexusActionRoute::CommandEffect,
            Self::Continue(_) => NexusActionRoute::Continue,
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum NexusObjectName {
    Work(NexusWorkRoute),
    Action(NexusActionRoute),
    Started,
    Stopped,
    Entered,
    Decided,
}
#[rustfmt::skip]
impl NexusObjectName {
    pub fn name(self) -> &'static str {
        match self {
            Self::Work(route) => {
                match route {
                    NexusWorkRoute::SignalArrived => "NexusWorkSignalArrived",
                    NexusWorkRoute::SemaWriteCompleted => "NexusWorkSemaWriteCompleted",
                    NexusWorkRoute::SemaReadCompleted => "NexusWorkSemaReadCompleted",
                    NexusWorkRoute::EffectCompleted => "NexusWorkEffectCompleted",
                }
            }
            Self::Action(route) => {
                match route {
                    NexusActionRoute::ReplyToSignal => "NexusActionReplyToSignal",
                    NexusActionRoute::CommandSemaWrite => "NexusActionCommandSemaWrite",
                    NexusActionRoute::CommandSemaRead => "NexusActionCommandSemaRead",
                    NexusActionRoute::CommandEffect => "NexusActionCommandEffect",
                    NexusActionRoute::Continue => "NexusActionContinue",
                }
            }
            Self::Started => "NexusStarted",
            Self::Stopped => "NexusStopped",
            Self::Entered => "NexusEntered",
            Self::Decided => "NexusDecided",
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ObjectName {
    Nexus(NexusObjectName),
}
#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub struct TraceEvent(pub ObjectName);
#[rustfmt::skip]
impl ObjectName {
    pub fn name(self) -> &'static str {
        match self {
            Self::Nexus(object_name) => object_name.name(),
        }
    }
}
#[rustfmt::skip]
impl TraceEvent {
    pub fn new(object_name: ObjectName) -> Self {
        Self(object_name)
    }
    pub fn object_name(&self) -> ObjectName {
        self.0
    }
    pub fn name(&self) -> &'static str {
        self.0.name()
    }
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub struct OriginRoute(Integer);
#[rustfmt::skip]
impl OriginRoute {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> Integer {
        self.0
    }
}

#[rustfmt::skip]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Nexus<Root> {
    pub origin_route: OriginRoute,
    pub root: Root,
}
#[rustfmt::skip]
impl<Root> Nexus<Root> {
    pub fn new(origin_route: OriginRoute, root: Root) -> Self {
        Self { origin_route, root }
    }
    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }
    pub fn root(&self) -> &Root {
        &self.root
    }
    pub fn into_root(self) -> Root {
        self.root
    }
    pub fn map_root<NextRoot>(
        self,
        map: impl FnOnce(Root) -> NextRoot,
    ) -> Nexus<NextRoot> {
        Nexus::new(self.origin_route, map(self.root))
    }
}

#[rustfmt::skip]
#[allow(clippy::module_inception)]
pub mod nexus {
    pub type Work = super::NexusWork;
    pub type Action = super::NexusAction;
    pub type Nexus<Root> = super::Nexus<Root>;
}

#[rustfmt::skip]
impl NexusWork {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> nexus::Nexus<Self> {
        nexus::Nexus::new(origin_route, self)
    }
}

#[rustfmt::skip]
impl NexusAction {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> nexus::Nexus<Self> {
        nexus::Nexus::new(origin_route, self)
    }
}

#[rustfmt::skip]
impl triad_runtime::NexusWork for NexusWork {}

#[rustfmt::skip]
impl triad_runtime::NexusEffectCommand for NexusEffectCommand {}

#[rustfmt::skip]
impl triad_runtime::NexusEffectResult for NexusEffectResult {}

#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum EngineStartFailure {
    ResourceBusy(String),
    ConfigurationInvalid(String),
}
#[rustfmt::skip]
impl std::fmt::Display for EngineStartFailure {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ResourceBusy(message) => {
                write!(formatter, "engine resource busy: {message}")
            }
            Self::ConfigurationInvalid(message) => {
                write!(formatter, "engine configuration invalid: {message}")
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for EngineStartFailure {}
#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum EngineStopFailure {
    ResourceLocked(String),
    ChildStillRunning(String),
}
#[rustfmt::skip]
impl std::fmt::Display for EngineStopFailure {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ResourceLocked(message) => {
                write!(formatter, "engine resource locked: {message}")
            }
            Self::ChildStillRunning(message) => {
                write!(formatter, "engine child still running: {message}")
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for EngineStopFailure {}

#[rustfmt::skip]
pub type NexusRunnerNextStep = triad_runtime::NextStep<
    SignalOutput,
    SemaWriteInput,
    SemaReadInput,
    NexusEffectCommand,
    NexusWork,
>;
#[rustfmt::skip]
impl triad_runtime::NexusAction for NexusAction {
    type Reply = SignalOutput;
    type SemaWrite = SemaWriteInput;
    type SemaRead = SemaReadInput;
    type Effect = NexusEffectCommand;
    type Work = NexusWork;
    fn into_next_step(self) -> NexusRunnerNextStep {
        match self {
            Self::CommandSemaWrite(input) => triad_runtime::NextStep::SemaWrite(input),
            Self::CommandSemaRead(input) => triad_runtime::NextStep::SemaRead(input),
            Self::ReplyToSignal(output) => triad_runtime::NextStep::Reply(output),
            Self::CommandEffect(effect) => triad_runtime::NextStep::RunEffect(effect),
            Self::Continue(work) => triad_runtime::NextStep::Continue(work),
        }
    }
}

#[rustfmt::skip]
pub trait NexusEngine: Send {
    fn on_start(&mut self) -> Result<(), EngineStartFailure> {
        Ok(())
    }
    fn on_stop(&mut self) -> Result<(), EngineStopFailure> {
        Ok(())
    }
    fn trace_nexus_activation(&self, _object_name: NexusObjectName) {}
    fn trace_nexus_entered(&self) {
        self.trace_nexus_activation(NexusObjectName::Entered);
    }
    fn trace_nexus_decided(&self) {
        self.trace_nexus_activation(NexusObjectName::Decided);
    }
    fn continuation_limit(&self) -> triad_runtime::ContinuationLimit {
        triad_runtime::ContinuationLimit::default()
    }
    fn apply_sema_write(
        &mut self,
        origin_route: OriginRoute,
        input: SemaWriteInput,
    ) -> impl std::future::Future<Output = SemaWriteOutput> + Send + '_;
    fn observe_sema_read(
        &mut self,
        origin_route: OriginRoute,
        input: SemaReadInput,
    ) -> impl std::future::Future<Output = SemaReadOutput> + Send + '_;
    fn run_effect(
        &mut self,
        input: NexusEffectCommand,
    ) -> impl std::future::Future<Output = NexusEffectResult> + Send + '_;
    fn budget_exhausted_reply(
        &self,
        exhausted: triad_runtime::ContinuationExhausted,
    ) -> SignalOutput;
    fn decide(
        &mut self,
        input: nexus::Nexus<nexus::Work>,
    ) -> nexus::Nexus<nexus::Action>;
    fn execute(
        &mut self,
        input: nexus::Nexus<nexus::Work>,
    ) -> impl std::future::Future<Output = nexus::Nexus<nexus::Action>> + Send + '_
    where
        Self: Sized,
    {
        async move {
            self.trace_nexus_entered();
            let origin_route = input.origin_route();
            let first_work = input.into_root();
            let runner = triad_runtime::Runner::new(self.continuation_limit());
            let mut runner_adapter = NexusRunnerAdapter::new(self, origin_route);
            let reply = runner.drive(&mut runner_adapter, first_work).await;
            let output = NexusAction::reply_to_signal(reply)
                .with_origin_route(origin_route);
            self.trace_nexus_decided();
            output
        }
    }
}

#[rustfmt::skip]
struct NexusRunnerAdapter<'engine, Engine> {
    engine: &'engine mut Engine,
    origin_route: OriginRoute,
}
#[rustfmt::skip]
impl<'engine, Engine> NexusRunnerAdapter<'engine, Engine> {
    fn new(engine: &'engine mut Engine, origin_route: OriginRoute) -> Self {
        Self { engine, origin_route }
    }
}
#[rustfmt::skip]
impl<'engine, Engine> triad_runtime::RunnerEngines
for NexusRunnerAdapter<'engine, Engine>
where
    Engine: NexusEngine,
{
    type Reply = SignalOutput;
    type SemaWrite = SemaWriteInput;
    type SemaRead = SemaReadInput;
    type Effect = NexusEffectCommand;
    type Work = NexusWork;
    fn decide_next_step(
        &mut self,
        work: Self::Work,
    ) -> triad_runtime::runner::RunnerNextStep<Self> {
        let action = NexusEngine::decide(
                self.engine,
                work.with_origin_route(self.origin_route),
            )
            .into_root();
        triad_runtime::NexusAction::into_next_step(action)
    }
    async fn apply_sema_write(&mut self, write: Self::SemaWrite) -> Self::Work {
        let output: SemaWriteOutput = NexusEngine::apply_sema_write(
                self.engine,
                self.origin_route,
                write,
            )
            .await;
        NexusWork::sema_write_completed(output)
    }
    async fn observe_sema_read(&mut self, read: Self::SemaRead) -> Self::Work {
        let output: SemaReadOutput = NexusEngine::observe_sema_read(
                self.engine,
                self.origin_route,
                read,
            )
            .await;
        NexusWork::sema_read_completed(output)
    }
    async fn run_effect(&mut self, effect: Self::Effect) -> Self::Work {
        let output: NexusEffectResult = NexusEngine::run_effect(self.engine, effect)
            .await;
        NexusWork::effect_completed(output)
    }
    fn budget_exhausted_reply(
        &self,
        exhausted: triad_runtime::ContinuationExhausted,
    ) -> Self::Reply {
        NexusEngine::budget_exhausted_reply(self.engine, exhausted)
    }
}

#[rustfmt::skip]
pub trait UpgradeFrom<Previous>: Sized {
    type Error;
    fn upgrade_from(previous: Previous) -> Result<Self, Self::Error>;
}
#[rustfmt::skip]
pub trait AcceptPrevious<Previous>: UpgradeFrom<Previous> {
    fn accept_previous(previous: Previous) -> Result<Self, Self::Error> {
        Self::upgrade_from(previous)
    }
}
#[rustfmt::skip]
impl<Current, Previous> AcceptPrevious<Previous> for Current
where
    Current: UpgradeFrom<Previous>,
{}
