// @generated by schema-rust-next

#[rustfmt::skip]
pub type String = std::string::String;
#[rustfmt::skip]
pub type Integer = u64;
#[rustfmt::skip]
pub type Boolean = bool;
#[rustfmt::skip]
pub type Path = std::string::String;

#[rustfmt::skip]
pub use crate::schema::signal::Input as SignalInput;
#[rustfmt::skip]
pub use crate::schema::signal::Output as SignalOutput;
#[rustfmt::skip]
pub use crate::schema::signal::MessageIngress as MessageIngress;
#[rustfmt::skip]
pub use crate::schema::signal::MessageAcceptance as MessageAcceptance;
#[rustfmt::skip]
pub use crate::schema::signal::AdjudicationQueued as AdjudicationQueued;
#[rustfmt::skip]
pub use crate::schema::signal::ErrorReport as ErrorReport;
#[rustfmt::skip]
pub use crate::schema::sema::WriteInput as SemaWriteInput;
#[rustfmt::skip]
pub use crate::schema::sema::ReadInput as SemaReadInput;
#[rustfmt::skip]
pub use crate::schema::sema::WriteOutput as SemaWriteOutput;
#[rustfmt::skip]
pub use crate::schema::sema::ReadOutput as SemaReadOutput;

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
pub use nota_next::{NotaDecode, NotaDecodeError, NotaEncode, NotaSource};

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SignalArrived(SignalInput);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SemaWriteCompleted(SemaWriteOutput);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SemaReadCompleted(SemaReadOutput);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct EffectCompleted(NexusEffectResult);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ReplyToSignal(SignalOutput);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CommandSemaWrite(SemaWriteInput);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CommandSemaRead(SemaReadInput);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CommandEffect(NexusEffectCommand);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Continue(NexusWork);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum NexusWork {
    SignalArrived(SignalArrived),
    SemaWriteCompleted(SemaWriteCompleted),
    SemaReadCompleted(SemaReadCompleted),
    EffectCompleted(EffectCompleted),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum NexusAction {
    ReplyToSignal(ReplyToSignal),
    CommandSemaWrite(CommandSemaWrite),
    CommandSemaRead(CommandSemaRead),
    CommandEffect(CommandEffect),
    Continue(Continue),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum DeliveryCommand {
    AttemptDelivery(AttemptDelivery),
    RequestAdjudication(RequestAdjudication),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AttemptDelivery(MessageIngress);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RequestAdjudication(MessageIngress);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum NexusEffectCommand {
    DeliverToHarness(DeliverToHarness),
    AskMindForChannel(AskMindForChannel),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DeliverToHarness(DeliveryCommand);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AskMindForChannel(MessageIngress);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DeliverySucceeded(MessageAcceptance);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DeliveryParked(AdjudicationQueued);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DeliveryFailed(ErrorReport);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum NexusEffectResult {
    DeliverySucceeded(DeliverySucceeded),
    DeliveryParked(DeliveryParked),
    DeliveryFailed(DeliveryFailed),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    SignalArrived(SignalArrived),
    SemaWriteCompleted(SemaWriteCompleted),
    SemaReadCompleted(SemaReadCompleted),
    EffectCompleted(EffectCompleted),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    ReplyToSignal(ReplyToSignal),
    CommandSemaWrite(CommandSemaWrite),
    CommandSemaRead(CommandSemaRead),
    CommandEffect(CommandEffect),
    Continue(Continue),
}

#[rustfmt::skip]
impl SignalArrived {
    pub fn new(payload: SignalInput) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SignalInput {
        &self.0
    }
    pub fn into_payload(self) -> SignalInput {
        self.0
    }
}
#[rustfmt::skip]
impl From<SignalInput> for SignalArrived {
    fn from(payload: SignalInput) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SemaWriteCompleted {
    pub fn new(payload: SemaWriteOutput) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SemaWriteOutput {
        &self.0
    }
    pub fn into_payload(self) -> SemaWriteOutput {
        self.0
    }
}
#[rustfmt::skip]
impl From<SemaWriteOutput> for SemaWriteCompleted {
    fn from(payload: SemaWriteOutput) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SemaReadCompleted {
    pub fn new(payload: SemaReadOutput) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SemaReadOutput {
        &self.0
    }
    pub fn into_payload(self) -> SemaReadOutput {
        self.0
    }
}
#[rustfmt::skip]
impl From<SemaReadOutput> for SemaReadCompleted {
    fn from(payload: SemaReadOutput) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl EffectCompleted {
    pub fn new(payload: NexusEffectResult) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &NexusEffectResult {
        &self.0
    }
    pub fn into_payload(self) -> NexusEffectResult {
        self.0
    }
}
#[rustfmt::skip]
impl From<NexusEffectResult> for EffectCompleted {
    fn from(payload: NexusEffectResult) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ReplyToSignal {
    pub fn new(payload: SignalOutput) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SignalOutput {
        &self.0
    }
    pub fn into_payload(self) -> SignalOutput {
        self.0
    }
}
#[rustfmt::skip]
impl From<SignalOutput> for ReplyToSignal {
    fn from(payload: SignalOutput) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl CommandSemaWrite {
    pub fn new(payload: SemaWriteInput) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SemaWriteInput {
        &self.0
    }
    pub fn into_payload(self) -> SemaWriteInput {
        self.0
    }
}
#[rustfmt::skip]
impl From<SemaWriteInput> for CommandSemaWrite {
    fn from(payload: SemaWriteInput) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl CommandSemaRead {
    pub fn new(payload: SemaReadInput) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SemaReadInput {
        &self.0
    }
    pub fn into_payload(self) -> SemaReadInput {
        self.0
    }
}
#[rustfmt::skip]
impl From<SemaReadInput> for CommandSemaRead {
    fn from(payload: SemaReadInput) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl CommandEffect {
    pub fn new(payload: NexusEffectCommand) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &NexusEffectCommand {
        &self.0
    }
    pub fn into_payload(self) -> NexusEffectCommand {
        self.0
    }
}
#[rustfmt::skip]
impl From<NexusEffectCommand> for CommandEffect {
    fn from(payload: NexusEffectCommand) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Continue {
    pub fn new(payload: NexusWork) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &NexusWork {
        &self.0
    }
    pub fn into_payload(self) -> NexusWork {
        self.0
    }
}
#[rustfmt::skip]
impl From<NexusWork> for Continue {
    fn from(payload: NexusWork) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl AttemptDelivery {
    pub fn new(payload: MessageIngress) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &MessageIngress {
        &self.0
    }
    pub fn into_payload(self) -> MessageIngress {
        self.0
    }
}
#[rustfmt::skip]
impl From<MessageIngress> for AttemptDelivery {
    fn from(payload: MessageIngress) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RequestAdjudication {
    pub fn new(payload: MessageIngress) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &MessageIngress {
        &self.0
    }
    pub fn into_payload(self) -> MessageIngress {
        self.0
    }
}
#[rustfmt::skip]
impl From<MessageIngress> for RequestAdjudication {
    fn from(payload: MessageIngress) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl DeliverToHarness {
    pub fn new(payload: DeliveryCommand) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &DeliveryCommand {
        &self.0
    }
    pub fn into_payload(self) -> DeliveryCommand {
        self.0
    }
}
#[rustfmt::skip]
impl From<DeliveryCommand> for DeliverToHarness {
    fn from(payload: DeliveryCommand) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl AskMindForChannel {
    pub fn new(payload: MessageIngress) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &MessageIngress {
        &self.0
    }
    pub fn into_payload(self) -> MessageIngress {
        self.0
    }
}
#[rustfmt::skip]
impl From<MessageIngress> for AskMindForChannel {
    fn from(payload: MessageIngress) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl DeliverySucceeded {
    pub fn new(payload: MessageAcceptance) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &MessageAcceptance {
        &self.0
    }
    pub fn into_payload(self) -> MessageAcceptance {
        self.0
    }
}
#[rustfmt::skip]
impl From<MessageAcceptance> for DeliverySucceeded {
    fn from(payload: MessageAcceptance) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl DeliveryParked {
    pub fn new(payload: AdjudicationQueued) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &AdjudicationQueued {
        &self.0
    }
    pub fn into_payload(self) -> AdjudicationQueued {
        self.0
    }
}
#[rustfmt::skip]
impl From<AdjudicationQueued> for DeliveryParked {
    fn from(payload: AdjudicationQueued) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl DeliveryFailed {
    pub fn new(payload: ErrorReport) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ErrorReport {
        &self.0
    }
    pub fn into_payload(self) -> ErrorReport {
        self.0
    }
}
#[rustfmt::skip]
impl From<ErrorReport> for DeliveryFailed {
    fn from(payload: ErrorReport) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl NexusWork {
    pub fn signal_arrived(payload: SignalInput) -> Self {
        Self::SignalArrived(SignalArrived::new(payload))
    }
    pub fn sema_write_completed(payload: SemaWriteOutput) -> Self {
        Self::SemaWriteCompleted(SemaWriteCompleted::new(payload))
    }
    pub fn sema_read_completed(payload: SemaReadOutput) -> Self {
        Self::SemaReadCompleted(SemaReadCompleted::new(payload))
    }
    pub fn effect_completed(payload: NexusEffectResult) -> Self {
        Self::EffectCompleted(EffectCompleted::new(payload))
    }
}

#[rustfmt::skip]
impl NexusAction {
    pub fn reply_to_signal(payload: SignalOutput) -> Self {
        Self::ReplyToSignal(ReplyToSignal::new(payload))
    }
    pub fn command_sema_write(payload: SemaWriteInput) -> Self {
        Self::CommandSemaWrite(CommandSemaWrite::new(payload))
    }
    pub fn command_sema_read(payload: SemaReadInput) -> Self {
        Self::CommandSemaRead(CommandSemaRead::new(payload))
    }
    pub fn command_effect(payload: NexusEffectCommand) -> Self {
        Self::CommandEffect(CommandEffect::new(payload))
    }
    pub fn r#continue(payload: NexusWork) -> Self {
        Self::Continue(Continue::new(payload))
    }
}

#[rustfmt::skip]
impl DeliveryCommand {
    pub fn attempt_delivery(payload: MessageIngress) -> Self {
        Self::AttemptDelivery(AttemptDelivery::new(payload))
    }
    pub fn request_adjudication(payload: MessageIngress) -> Self {
        Self::RequestAdjudication(RequestAdjudication::new(payload))
    }
}

#[rustfmt::skip]
impl NexusEffectCommand {
    pub fn deliver_to_harness(payload: DeliveryCommand) -> Self {
        Self::DeliverToHarness(DeliverToHarness::new(payload))
    }
    pub fn ask_mind_for_channel(payload: MessageIngress) -> Self {
        Self::AskMindForChannel(AskMindForChannel::new(payload))
    }
}

#[rustfmt::skip]
impl NexusEffectResult {
    pub fn delivery_succeeded(payload: MessageAcceptance) -> Self {
        Self::DeliverySucceeded(DeliverySucceeded::new(payload))
    }
    pub fn delivery_parked(payload: AdjudicationQueued) -> Self {
        Self::DeliveryParked(DeliveryParked::new(payload))
    }
    pub fn delivery_failed(payload: ErrorReport) -> Self {
        Self::DeliveryFailed(DeliveryFailed::new(payload))
    }
}

#[rustfmt::skip]
impl Input {
    pub fn signal_arrived(payload: SignalInput) -> Self {
        Self::SignalArrived(SignalArrived::new(payload))
    }
    pub fn sema_write_completed(payload: SemaWriteOutput) -> Self {
        Self::SemaWriteCompleted(SemaWriteCompleted::new(payload))
    }
    pub fn sema_read_completed(payload: SemaReadOutput) -> Self {
        Self::SemaReadCompleted(SemaReadCompleted::new(payload))
    }
    pub fn effect_completed(payload: NexusEffectResult) -> Self {
        Self::EffectCompleted(EffectCompleted::new(payload))
    }
}

#[rustfmt::skip]
impl Output {
    pub fn reply_to_signal(payload: SignalOutput) -> Self {
        Self::ReplyToSignal(ReplyToSignal::new(payload))
    }
    pub fn command_sema_write(payload: SemaWriteInput) -> Self {
        Self::CommandSemaWrite(CommandSemaWrite::new(payload))
    }
    pub fn command_sema_read(payload: SemaReadInput) -> Self {
        Self::CommandSemaRead(CommandSemaRead::new(payload))
    }
    pub fn command_effect(payload: NexusEffectCommand) -> Self {
        Self::CommandEffect(CommandEffect::new(payload))
    }
    pub fn r#continue(payload: NexusWork) -> Self {
        Self::Continue(Continue::new(payload))
    }
}

#[rustfmt::skip]
impl From<SignalArrived> for NexusWork {
    fn from(payload: SignalArrived) -> Self {
        Self::SignalArrived(payload)
    }
}

#[rustfmt::skip]
impl From<SemaWriteCompleted> for NexusWork {
    fn from(payload: SemaWriteCompleted) -> Self {
        Self::SemaWriteCompleted(payload)
    }
}

#[rustfmt::skip]
impl From<SemaReadCompleted> for NexusWork {
    fn from(payload: SemaReadCompleted) -> Self {
        Self::SemaReadCompleted(payload)
    }
}

#[rustfmt::skip]
impl From<EffectCompleted> for NexusWork {
    fn from(payload: EffectCompleted) -> Self {
        Self::EffectCompleted(payload)
    }
}

#[rustfmt::skip]
impl From<ReplyToSignal> for NexusAction {
    fn from(payload: ReplyToSignal) -> Self {
        Self::ReplyToSignal(payload)
    }
}

#[rustfmt::skip]
impl From<CommandSemaWrite> for NexusAction {
    fn from(payload: CommandSemaWrite) -> Self {
        Self::CommandSemaWrite(payload)
    }
}

#[rustfmt::skip]
impl From<CommandSemaRead> for NexusAction {
    fn from(payload: CommandSemaRead) -> Self {
        Self::CommandSemaRead(payload)
    }
}

#[rustfmt::skip]
impl From<CommandEffect> for NexusAction {
    fn from(payload: CommandEffect) -> Self {
        Self::CommandEffect(payload)
    }
}

#[rustfmt::skip]
impl From<Continue> for NexusAction {
    fn from(payload: Continue) -> Self {
        Self::Continue(payload)
    }
}

#[rustfmt::skip]
impl From<AttemptDelivery> for DeliveryCommand {
    fn from(payload: AttemptDelivery) -> Self {
        Self::AttemptDelivery(payload)
    }
}

#[rustfmt::skip]
impl From<RequestAdjudication> for DeliveryCommand {
    fn from(payload: RequestAdjudication) -> Self {
        Self::RequestAdjudication(payload)
    }
}

#[rustfmt::skip]
impl From<DeliverToHarness> for NexusEffectCommand {
    fn from(payload: DeliverToHarness) -> Self {
        Self::DeliverToHarness(payload)
    }
}

#[rustfmt::skip]
impl From<AskMindForChannel> for NexusEffectCommand {
    fn from(payload: AskMindForChannel) -> Self {
        Self::AskMindForChannel(payload)
    }
}

#[rustfmt::skip]
impl From<DeliverySucceeded> for NexusEffectResult {
    fn from(payload: DeliverySucceeded) -> Self {
        Self::DeliverySucceeded(payload)
    }
}

#[rustfmt::skip]
impl From<DeliveryParked> for NexusEffectResult {
    fn from(payload: DeliveryParked) -> Self {
        Self::DeliveryParked(payload)
    }
}

#[rustfmt::skip]
impl From<DeliveryFailed> for NexusEffectResult {
    fn from(payload: DeliveryFailed) -> Self {
        Self::DeliveryFailed(payload)
    }
}

#[rustfmt::skip]
impl From<SignalArrived> for Input {
    fn from(payload: SignalArrived) -> Self {
        Self::SignalArrived(payload)
    }
}

#[rustfmt::skip]
impl From<SemaWriteCompleted> for Input {
    fn from(payload: SemaWriteCompleted) -> Self {
        Self::SemaWriteCompleted(payload)
    }
}

#[rustfmt::skip]
impl From<SemaReadCompleted> for Input {
    fn from(payload: SemaReadCompleted) -> Self {
        Self::SemaReadCompleted(payload)
    }
}

#[rustfmt::skip]
impl From<EffectCompleted> for Input {
    fn from(payload: EffectCompleted) -> Self {
        Self::EffectCompleted(payload)
    }
}

#[rustfmt::skip]
impl From<ReplyToSignal> for Output {
    fn from(payload: ReplyToSignal) -> Self {
        Self::ReplyToSignal(payload)
    }
}

#[rustfmt::skip]
impl From<CommandSemaWrite> for Output {
    fn from(payload: CommandSemaWrite) -> Self {
        Self::CommandSemaWrite(payload)
    }
}

#[rustfmt::skip]
impl From<CommandSemaRead> for Output {
    fn from(payload: CommandSemaRead) -> Self {
        Self::CommandSemaRead(payload)
    }
}

#[rustfmt::skip]
impl From<CommandEffect> for Output {
    fn from(payload: CommandEffect) -> Self {
        Self::CommandEffect(payload)
    }
}

#[rustfmt::skip]
impl From<Continue> for Output {
    fn from(payload: Continue) -> Self {
        Self::Continue(payload)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl SignalArrived {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl SemaWriteCompleted {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl SemaReadCompleted {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl EffectCompleted {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl ReplyToSignal {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl CommandSemaWrite {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl CommandSemaRead {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl CommandEffect {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Continue {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl NexusWork {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl NexusAction {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl DeliveryCommand {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl AttemptDelivery {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl RequestAdjudication {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl NexusEffectCommand {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl DeliverToHarness {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl AskMindForChannel {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl DeliverySucceeded {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl DeliveryParked {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl DeliveryFailed {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl NexusEffectResult {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Input {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Input {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Output {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Output {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum NexusWorkRoute {
    SignalArrived,
    SemaWriteCompleted,
    SemaReadCompleted,
    EffectCompleted,
}

#[rustfmt::skip]
impl NexusWork {
    pub fn route(&self) -> NexusWorkRoute {
        match self {
            Self::SignalArrived(_) => NexusWorkRoute::SignalArrived,
            Self::SemaWriteCompleted(_) => NexusWorkRoute::SemaWriteCompleted,
            Self::SemaReadCompleted(_) => NexusWorkRoute::SemaReadCompleted,
            Self::EffectCompleted(_) => NexusWorkRoute::EffectCompleted,
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum NexusActionRoute {
    ReplyToSignal,
    CommandSemaWrite,
    CommandSemaRead,
    CommandEffect,
    Continue,
}

#[rustfmt::skip]
impl NexusAction {
    pub fn route(&self) -> NexusActionRoute {
        match self {
            Self::ReplyToSignal(_) => NexusActionRoute::ReplyToSignal,
            Self::CommandSemaWrite(_) => NexusActionRoute::CommandSemaWrite,
            Self::CommandSemaRead(_) => NexusActionRoute::CommandSemaRead,
            Self::CommandEffect(_) => NexusActionRoute::CommandEffect,
            Self::Continue(_) => NexusActionRoute::Continue,
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum NexusObjectName {
    Work(NexusWorkRoute),
    Action(NexusActionRoute),
    Started,
    Stopped,
    Entered,
    Decided,
}
#[rustfmt::skip]
impl NexusObjectName {
    pub fn name(self) -> &'static str {
        match self {
            Self::Work(route) => {
                match route {
                    NexusWorkRoute::SignalArrived => "NexusWorkSignalArrived",
                    NexusWorkRoute::SemaWriteCompleted => "NexusWorkSemaWriteCompleted",
                    NexusWorkRoute::SemaReadCompleted => "NexusWorkSemaReadCompleted",
                    NexusWorkRoute::EffectCompleted => "NexusWorkEffectCompleted",
                }
            }
            Self::Action(route) => {
                match route {
                    NexusActionRoute::ReplyToSignal => "NexusActionReplyToSignal",
                    NexusActionRoute::CommandSemaWrite => "NexusActionCommandSemaWrite",
                    NexusActionRoute::CommandSemaRead => "NexusActionCommandSemaRead",
                    NexusActionRoute::CommandEffect => "NexusActionCommandEffect",
                    NexusActionRoute::Continue => "NexusActionContinue",
                }
            }
            Self::Started => "NexusStarted",
            Self::Stopped => "NexusStopped",
            Self::Entered => "NexusEntered",
            Self::Decided => "NexusDecided",
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ObjectName {
    Nexus(NexusObjectName),
}
#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub struct TraceEvent(pub ObjectName);
#[rustfmt::skip]
impl ObjectName {
    pub fn name(self) -> &'static str {
        match self {
            Self::Nexus(object_name) => object_name.name(),
        }
    }
}
#[rustfmt::skip]
impl TraceEvent {
    pub fn new(object_name: ObjectName) -> Self {
        Self(object_name)
    }
    pub fn object_name(&self) -> ObjectName {
        self.0
    }
    pub fn name(&self) -> &'static str {
        self.0.name()
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub struct OriginRoute(Integer);
#[rustfmt::skip]
impl OriginRoute {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl OriginRoute {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(self) -> String {
        <Self as NotaEncode>::to_nota(&self)
    }
}

#[rustfmt::skip]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Nexus<Root> {
    pub origin_route: OriginRoute,
    pub root: Root,
}
#[rustfmt::skip]
impl<Root> Nexus<Root> {
    pub fn new(origin_route: OriginRoute, root: Root) -> Self {
        Self { origin_route, root }
    }
    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }
    pub fn root(&self) -> &Root {
        &self.root
    }
    pub fn into_root(self) -> Root {
        self.root
    }
    pub fn map_root<NextRoot>(
        self,
        map: impl FnOnce(Root) -> NextRoot,
    ) -> Nexus<NextRoot> {
        Nexus::new(self.origin_route, map(self.root))
    }
}

#[rustfmt::skip]
#[allow(clippy::module_inception)]
pub mod nexus {
    pub type Work = super::NexusWork;
    pub type Action = super::NexusAction;
    pub type Nexus<Root> = super::Nexus<Root>;
}

#[rustfmt::skip]
impl NexusWork {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> nexus::Nexus<Self> {
        nexus::Nexus::new(origin_route, self)
    }
}

#[rustfmt::skip]
impl NexusAction {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> nexus::Nexus<Self> {
        nexus::Nexus::new(origin_route, self)
    }
}

#[rustfmt::skip]
impl triad_runtime::NexusWork for NexusWork {}

#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum EngineStartFailure {
    ResourceBusy(String),
    ConfigurationInvalid(String),
}
#[rustfmt::skip]
impl std::fmt::Display for EngineStartFailure {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ResourceBusy(message) => {
                write!(formatter, "engine resource busy: {message}")
            }
            Self::ConfigurationInvalid(message) => {
                write!(formatter, "engine configuration invalid: {message}")
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for EngineStartFailure {}
#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum EngineStopFailure {
    ResourceLocked(String),
    ChildStillRunning(String),
}
#[rustfmt::skip]
impl std::fmt::Display for EngineStopFailure {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ResourceLocked(message) => {
                write!(formatter, "engine resource locked: {message}")
            }
            Self::ChildStillRunning(message) => {
                write!(formatter, "engine child still running: {message}")
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for EngineStopFailure {}

#[rustfmt::skip]
pub trait NexusEngine: Send {
    fn on_start(&mut self) -> Result<(), EngineStartFailure> {
        Ok(())
    }
    fn on_stop(&mut self) -> Result<(), EngineStopFailure> {
        Ok(())
    }
    fn trace_nexus_activation(&self, _object_name: NexusObjectName) {}
    fn trace_nexus_entered(&self) {
        self.trace_nexus_activation(NexusObjectName::Entered);
    }
    fn trace_nexus_decided(&self) {
        self.trace_nexus_activation(NexusObjectName::Decided);
    }
    fn decide(
        &mut self,
        input: nexus::Nexus<nexus::Work>,
    ) -> nexus::Nexus<nexus::Action>;
    fn execute(
        &mut self,
        input: nexus::Nexus<nexus::Work>,
    ) -> impl std::future::Future<Output = nexus::Nexus<nexus::Action>> + Send + '_ {
        async move {
            self.trace_nexus_entered();
            let output = self.decide(input);
            self.trace_nexus_decided();
            output
        }
    }
}

#[rustfmt::skip]
pub trait UpgradeFrom<Previous>: Sized {
    type Error;
    fn upgrade_from(previous: Previous) -> Result<Self, Self::Error>;
}
#[rustfmt::skip]
pub trait AcceptPrevious<Previous>: UpgradeFrom<Previous> {
    fn accept_previous(previous: Previous) -> Result<Self, Self::Error> {
        Self::upgrade_from(previous)
    }
}
#[rustfmt::skip]
impl<Current, Previous> AcceptPrevious<Previous> for Current
where
    Current: UpgradeFrom<Previous>,
{}
