// @generated by schema-rust-next

#[rustfmt::skip]
pub type String = std::string::String;
#[rustfmt::skip]
pub type Integer = u64;
#[rustfmt::skip]
pub type Boolean = bool;
#[rustfmt::skip]
pub type Path = std::string::String;

#[rustfmt::skip]
pub use crate::schema::signal::MessageIngress as MessageIngress;
#[rustfmt::skip]
pub use crate::schema::signal::RouterObservation as RouterObservation;
#[rustfmt::skip]
pub use crate::schema::signal::MessageAcceptance as MessageAcceptance;
#[rustfmt::skip]
pub use crate::schema::signal::AdjudicationQueued as AdjudicationQueued;
#[rustfmt::skip]
pub use crate::schema::signal::ErrorReport as ErrorReport;

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
pub use nota_next::{NotaDecode, NotaDecodeError, NotaEncode, NotaSource};

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum WriteInput {
    RecordAcceptedMessage(RecordAcceptedMessage),
    RecordChannelPolicy(RecordChannelPolicy),
    RecordDeliveryResult(RecordDeliveryResult),
    RecordAdjudicationRequest(RecordAdjudicationRequest),
}

#[rustfmt::skip]
pub type RecordAcceptedMessage = MessageIngress;

#[rustfmt::skip]
pub type RecordChannelPolicy = ChannelPolicyChange;

#[rustfmt::skip]
pub type RecordDeliveryResult = DeliveryResult;

#[rustfmt::skip]
pub type RecordAdjudicationRequest = MessageIngress;

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum ReadInput {
    ReadRouterObservation(ReadRouterObservation),
    ReadChannelState(ReadChannelState),
}

#[rustfmt::skip]
pub type ReadRouterObservation = RouterObservation;

#[rustfmt::skip]
pub type ReadChannelState = ChannelIdentifier;

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum WriteOutput {
    Committed(CommitReceipt),
    WriteRejected(ErrorReport),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum ReadOutput {
    RouterObserved(RouterObservationResult),
    ReadRejected(ErrorReport),
}

#[rustfmt::skip]
pub type ChannelIdentifier = String;

#[rustfmt::skip]
pub type CommitSequence = Integer;

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct CommitReceipt(pub CommitSequence);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum ChannelPolicyChange {
    Grant(GrantChannel),
    Extend(ExtendChannel),
    Revoke(RevokeChannel),
    Deny(DenyAdjudication),
}

#[rustfmt::skip]
pub type GrantChannel = ChannelIdentifier;

#[rustfmt::skip]
pub type ExtendChannel = ChannelIdentifier;

#[rustfmt::skip]
pub type RevokeChannel = ChannelIdentifier;

#[rustfmt::skip]
pub type DenyAdjudication = ChannelIdentifier;

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum DeliveryResult {
    Delivered(MessageAcceptance),
    Parked(AdjudicationQueued),
    Failed(ErrorReport),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RouterObservationResult(pub CommitSequence);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    WriteInput(WriteInput),
    ReadInput(ReadInput),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    WriteOutput(WriteOutput),
    ReadOutput(ReadOutput),
}

#[rustfmt::skip]
impl CommitReceipt {
    pub fn new(payload: CommitSequence) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &CommitSequence {
        &self.0
    }
    pub fn into_payload(self) -> CommitSequence {
        self.0
    }
}
#[rustfmt::skip]
impl From<CommitSequence> for CommitReceipt {
    fn from(payload: CommitSequence) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RouterObservationResult {
    pub fn new(payload: CommitSequence) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &CommitSequence {
        &self.0
    }
    pub fn into_payload(self) -> CommitSequence {
        self.0
    }
}
#[rustfmt::skip]
impl From<CommitSequence> for RouterObservationResult {
    fn from(payload: CommitSequence) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl WriteInput {
    pub fn record_accepted_message(payload: RecordAcceptedMessage) -> Self {
        Self::RecordAcceptedMessage(payload)
    }
    pub fn record_channel_policy(payload: RecordChannelPolicy) -> Self {
        Self::RecordChannelPolicy(payload)
    }
    pub fn record_delivery_result(payload: RecordDeliveryResult) -> Self {
        Self::RecordDeliveryResult(payload)
    }
    pub fn record_adjudication_request(payload: RecordAdjudicationRequest) -> Self {
        Self::RecordAdjudicationRequest(payload)
    }
}

#[rustfmt::skip]
impl ReadInput {
    pub fn read_router_observation(payload: ReadRouterObservation) -> Self {
        Self::ReadRouterObservation(payload)
    }
    pub fn read_channel_state(payload: ReadChannelState) -> Self {
        Self::ReadChannelState(payload)
    }
}

#[rustfmt::skip]
impl WriteOutput {
    pub fn committed(payload: CommitSequence) -> Self {
        Self::Committed(CommitReceipt::new(payload))
    }
    pub fn write_rejected(payload: ErrorReport) -> Self {
        Self::WriteRejected(payload)
    }
}

#[rustfmt::skip]
impl ReadOutput {
    pub fn router_observed(payload: CommitSequence) -> Self {
        Self::RouterObserved(RouterObservationResult::new(payload))
    }
    pub fn read_rejected(payload: ErrorReport) -> Self {
        Self::ReadRejected(payload)
    }
}

#[rustfmt::skip]
impl ChannelPolicyChange {
    pub fn grant(payload: GrantChannel) -> Self {
        Self::Grant(payload)
    }
    pub fn extend(payload: ExtendChannel) -> Self {
        Self::Extend(payload)
    }
    pub fn revoke(payload: RevokeChannel) -> Self {
        Self::Revoke(payload)
    }
    pub fn deny(payload: DenyAdjudication) -> Self {
        Self::Deny(payload)
    }
}

#[rustfmt::skip]
impl DeliveryResult {
    pub fn delivered(payload: MessageAcceptance) -> Self {
        Self::Delivered(payload)
    }
    pub fn parked(payload: AdjudicationQueued) -> Self {
        Self::Parked(payload)
    }
    pub fn failed(payload: ErrorReport) -> Self {
        Self::Failed(payload)
    }
}

#[rustfmt::skip]
impl Input {
    pub fn write_input(payload: WriteInput) -> Self {
        Self::WriteInput(payload)
    }
    pub fn read_input(payload: ReadInput) -> Self {
        Self::ReadInput(payload)
    }
}

#[rustfmt::skip]
impl Output {
    pub fn write_output(payload: WriteOutput) -> Self {
        Self::WriteOutput(payload)
    }
    pub fn read_output(payload: ReadOutput) -> Self {
        Self::ReadOutput(payload)
    }
}

#[rustfmt::skip]
impl From<CommitReceipt> for WriteOutput {
    fn from(payload: CommitReceipt) -> Self {
        Self::Committed(payload)
    }
}

#[rustfmt::skip]
impl From<ErrorReport> for WriteOutput {
    fn from(payload: ErrorReport) -> Self {
        Self::WriteRejected(payload)
    }
}

#[rustfmt::skip]
impl From<RouterObservationResult> for ReadOutput {
    fn from(payload: RouterObservationResult) -> Self {
        Self::RouterObserved(payload)
    }
}

#[rustfmt::skip]
impl From<ErrorReport> for ReadOutput {
    fn from(payload: ErrorReport) -> Self {
        Self::ReadRejected(payload)
    }
}

#[rustfmt::skip]
impl From<MessageAcceptance> for DeliveryResult {
    fn from(payload: MessageAcceptance) -> Self {
        Self::Delivered(payload)
    }
}

#[rustfmt::skip]
impl From<AdjudicationQueued> for DeliveryResult {
    fn from(payload: AdjudicationQueued) -> Self {
        Self::Parked(payload)
    }
}

#[rustfmt::skip]
impl From<ErrorReport> for DeliveryResult {
    fn from(payload: ErrorReport) -> Self {
        Self::Failed(payload)
    }
}

#[rustfmt::skip]
impl From<WriteInput> for Input {
    fn from(payload: WriteInput) -> Self {
        Self::WriteInput(payload)
    }
}

#[rustfmt::skip]
impl From<ReadInput> for Input {
    fn from(payload: ReadInput) -> Self {
        Self::ReadInput(payload)
    }
}

#[rustfmt::skip]
impl From<WriteOutput> for Output {
    fn from(payload: WriteOutput) -> Self {
        Self::WriteOutput(payload)
    }
}

#[rustfmt::skip]
impl From<ReadOutput> for Output {
    fn from(payload: ReadOutput) -> Self {
        Self::ReadOutput(payload)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl WriteInput {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl ReadInput {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl WriteOutput {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl ReadOutput {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl CommitReceipt {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl ChannelPolicyChange {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl DeliveryResult {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl RouterObservationResult {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Input {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Input {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl Output {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(&self) -> String {
        <Self as NotaEncode>::to_nota(self)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Output {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum WriteInputRoute {
    RecordAcceptedMessage,
    RecordChannelPolicy,
    RecordDeliveryResult,
    RecordAdjudicationRequest,
}

#[rustfmt::skip]
impl WriteInput {
    pub fn route(&self) -> WriteInputRoute {
        match self {
            Self::RecordAcceptedMessage(_) => WriteInputRoute::RecordAcceptedMessage,
            Self::RecordChannelPolicy(_) => WriteInputRoute::RecordChannelPolicy,
            Self::RecordDeliveryResult(_) => WriteInputRoute::RecordDeliveryResult,
            Self::RecordAdjudicationRequest(_) => {
                WriteInputRoute::RecordAdjudicationRequest
            }
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ReadInputRoute {
    ReadRouterObservation,
    ReadChannelState,
}

#[rustfmt::skip]
impl ReadInput {
    pub fn route(&self) -> ReadInputRoute {
        match self {
            Self::ReadRouterObservation(_) => ReadInputRoute::ReadRouterObservation,
            Self::ReadChannelState(_) => ReadInputRoute::ReadChannelState,
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum WriteOutputRoute {
    Committed,
    WriteRejected,
}

#[rustfmt::skip]
impl WriteOutput {
    pub fn route(&self) -> WriteOutputRoute {
        match self {
            Self::Committed(_) => WriteOutputRoute::Committed,
            Self::WriteRejected(_) => WriteOutputRoute::WriteRejected,
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ReadOutputRoute {
    RouterObserved,
    ReadRejected,
}

#[rustfmt::skip]
impl ReadOutput {
    pub fn route(&self) -> ReadOutputRoute {
        match self {
            Self::RouterObserved(_) => ReadOutputRoute::RouterObserved,
            Self::ReadRejected(_) => ReadOutputRoute::ReadRejected,
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum SemaObjectName {
    WriteInput(WriteInputRoute),
    ReadInput(ReadInputRoute),
    WriteOutput(WriteOutputRoute),
    ReadOutput(ReadOutputRoute),
    Started,
    Stopped,
    WriteApplied,
    ReadObserved,
}
#[rustfmt::skip]
impl SemaObjectName {
    pub fn name(self) -> &'static str {
        match self {
            Self::WriteInput(route) => {
                match route {
                    WriteInputRoute::RecordAcceptedMessage => {
                        "SemaWriteInputRecordAcceptedMessage"
                    }
                    WriteInputRoute::RecordChannelPolicy => {
                        "SemaWriteInputRecordChannelPolicy"
                    }
                    WriteInputRoute::RecordDeliveryResult => {
                        "SemaWriteInputRecordDeliveryResult"
                    }
                    WriteInputRoute::RecordAdjudicationRequest => {
                        "SemaWriteInputRecordAdjudicationRequest"
                    }
                }
            }
            Self::ReadInput(route) => {
                match route {
                    ReadInputRoute::ReadRouterObservation => {
                        "SemaReadInputReadRouterObservation"
                    }
                    ReadInputRoute::ReadChannelState => "SemaReadInputReadChannelState",
                }
            }
            Self::WriteOutput(route) => {
                match route {
                    WriteOutputRoute::Committed => "SemaWriteOutputCommitted",
                    WriteOutputRoute::WriteRejected => "SemaWriteOutputWriteRejected",
                }
            }
            Self::ReadOutput(route) => {
                match route {
                    ReadOutputRoute::RouterObserved => "SemaReadOutputRouterObserved",
                    ReadOutputRoute::ReadRejected => "SemaReadOutputReadRejected",
                }
            }
            Self::Started => "SemaStarted",
            Self::Stopped => "SemaStopped",
            Self::WriteApplied => "SemaWriteApplied",
            Self::ReadObserved => "SemaReadObserved",
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ObjectName {
    Sema(SemaObjectName),
}
#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub struct TraceEvent(pub ObjectName);
#[rustfmt::skip]
impl ObjectName {
    pub fn name(self) -> &'static str {
        match self {
            Self::Sema(object_name) => object_name.name(),
        }
    }
}
#[rustfmt::skip]
impl TraceEvent {
    pub fn new(object_name: ObjectName) -> Self {
        Self(object_name)
    }
    pub fn object_name(&self) -> ObjectName {
        self.0
    }
    pub fn name(&self) -> &'static str {
        self.0.name()
    }
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub struct OriginRoute(pub Integer);
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl OriginRoute {
    pub fn from_nota_block(block: &nota_next::Block) -> Result<Self, NotaDecodeError> {
        <Self as NotaDecode>::from_nota_block(block)
    }
    pub fn to_nota(self) -> String {
        <Self as NotaEncode>::to_nota(&self)
    }
}

#[rustfmt::skip]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Sema<Root> {
    pub origin_route: OriginRoute,
    pub root: Root,
}
#[rustfmt::skip]
impl<Root> Sema<Root> {
    pub fn new(origin_route: OriginRoute, root: Root) -> Self {
        Self { origin_route, root }
    }
    pub fn origin_route(&self) -> OriginRoute {
        self.origin_route
    }
    pub fn root(&self) -> &Root {
        &self.root
    }
    pub fn into_root(self) -> Root {
        self.root
    }
    pub fn map_root<NextRoot>(
        self,
        map: impl FnOnce(Root) -> NextRoot,
    ) -> Sema<NextRoot> {
        Sema::new(self.origin_route, map(self.root))
    }
}

#[rustfmt::skip]
#[allow(clippy::module_inception)]
pub mod sema {
    pub type WriteInput = super::WriteInput;
    pub type WriteOutput = super::WriteOutput;
    pub type ReadInput = super::ReadInput;
    pub type ReadOutput = super::ReadOutput;
    pub type Sema<Root> = super::Sema<Root>;
}

#[rustfmt::skip]
impl WriteInput {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> sema::Sema<Self> {
        sema::Sema::new(origin_route, self)
    }
}

#[rustfmt::skip]
impl WriteOutput {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> sema::Sema<Self> {
        sema::Sema::new(origin_route, self)
    }
}

#[rustfmt::skip]
impl ReadInput {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> sema::Sema<Self> {
        sema::Sema::new(origin_route, self)
    }
}

#[rustfmt::skip]
impl ReadOutput {
    pub fn with_origin_route(self, origin_route: OriginRoute) -> sema::Sema<Self> {
        sema::Sema::new(origin_route, self)
    }
}

#[rustfmt::skip]
impl triad_runtime::SemaWriteInput for WriteInput {}

#[rustfmt::skip]
impl triad_runtime::SemaWriteOutput for WriteOutput {}

#[rustfmt::skip]
impl triad_runtime::SemaReadInput for ReadInput {}

#[rustfmt::skip]
impl triad_runtime::SemaReadOutput for ReadOutput {}

#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum EngineStartFailure {
    ResourceBusy(String),
    ConfigurationInvalid(String),
}
#[rustfmt::skip]
impl std::fmt::Display for EngineStartFailure {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ResourceBusy(message) => {
                write!(formatter, "engine resource busy: {message}")
            }
            Self::ConfigurationInvalid(message) => {
                write!(formatter, "engine configuration invalid: {message}")
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for EngineStartFailure {}
#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum EngineStopFailure {
    ResourceLocked(String),
    ChildStillRunning(String),
}
#[rustfmt::skip]
impl std::fmt::Display for EngineStopFailure {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ResourceLocked(message) => {
                write!(formatter, "engine resource locked: {message}")
            }
            Self::ChildStillRunning(message) => {
                write!(formatter, "engine child still running: {message}")
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for EngineStopFailure {}

#[rustfmt::skip]
pub trait SemaEngine: Send {
    fn on_start(&mut self) -> Result<(), EngineStartFailure> {
        Ok(())
    }
    fn on_stop(&mut self) -> Result<(), EngineStopFailure> {
        Ok(())
    }
    fn trace_sema_activation(&self, _object_name: SemaObjectName) {}
    fn trace_sema_write_applied(&self) {
        self.trace_sema_activation(SemaObjectName::WriteApplied);
    }
    fn trace_sema_read_observed(&self) {
        self.trace_sema_activation(SemaObjectName::ReadObserved);
    }
    fn apply_inner(
        &mut self,
        input: sema::Sema<sema::WriteInput>,
    ) -> sema::Sema<sema::WriteOutput>;
    fn observe_inner(
        &self,
        input: sema::Sema<sema::ReadInput>,
    ) -> sema::Sema<sema::ReadOutput>;
    fn apply(
        &mut self,
        input: sema::Sema<sema::WriteInput>,
    ) -> sema::Sema<sema::WriteOutput> {
        let output = self.apply_inner(input);
        self.trace_sema_write_applied();
        output
    }
    fn observe(
        &self,
        input: sema::Sema<sema::ReadInput>,
    ) -> sema::Sema<sema::ReadOutput> {
        let output = self.observe_inner(input);
        self.trace_sema_read_observed();
        output
    }
}

#[rustfmt::skip]
pub trait UpgradeFrom<Previous>: Sized {
    type Error;
    fn upgrade_from(previous: Previous) -> Result<Self, Self::Error>;
}
#[rustfmt::skip]
pub trait AcceptPrevious<Previous>: UpgradeFrom<Previous> {
    fn accept_previous(previous: Previous) -> Result<Self, Self::Error> {
        Self::upgrade_from(previous)
    }
}
#[rustfmt::skip]
impl<Current, Previous> AcceptPrevious<Previous> for Current
where
    Current: UpgradeFrom<Previous>,
{}
